Components/CartSummaryViewComponent.cs
using Mike05.Models;
using Microsoft.AspNetCore.Mvc;

namespace Mike05.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        //passes on the Cart to the View method to generate the fragment of HTML that will be included in the layout
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mike05.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mike05.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBookRepository repository;
        public NavigationMenuViewComponent(IBookRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            //will dynamically build a viewbag entry. In this case it will do it based on the category 
            //this is based on the route (endpoints) in the startup.cs file
            ViewBag.SelectedType = RouteData?.Values["category"];

            //figures out how to order it and orders it that way
            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Views/Shared/BookSummary.cshtml
@model Book
@*Work through each instance of Book and get the following information out: then print it one at a time*@
<div class="card card-outline-primary m-1 p-1">


    @*Create header for each card using book title*@
    <div class="card-header">
        <h4 class="my-auto">@Model.Title</h4>
    </div>

    @*Create body content for each card using the rest of the model*@
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Author: @Model.AuthorFirst @Model.AuthorMiddle @Model.AuthorLast</li>
            <li class="list-group-item">Publisher: @Model.Publisher</li>
            <li class="list-group-item">ISBN: @Model.ISBN</li>
            <li class="list-group-item">Classification: @Model.Classification</li>
            <li class="list-group-item">Category: @Model.Category</li>
            <li class="list-group-item">Price: $@Model.Price</li>
            <li class="list-group-item">Total Pages: @Model.TotalPages</li>
        </ul>
    </div>
    <form id="@Model.BookId" asp-page="/Purchase" method="post">
        <input type="hidden" asp-for="BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="cart-text p-1">
            @Model.Title
            <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                Add to Cart
            </button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

@*call in stylesheets and set page title for tab*@
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hilton the Amazonian</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />

</head>
<body>

    @*Cart Summary*@
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Hilton the Amazonian</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>


    @*nav bar with links to other pages*@
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hilton the Amazonian</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    @*Body housing the imported view from other pages*@
    <div class="container">
        <div class="row">
            @*Left side text of main page*@
            <div id="left_side" class="col-4">
                <h1>Behold, thy books shall be recommended</h1>
                <h6>Select a category:</h6>
                @* next line will go to the Componenets folder and find the "NavigationMenu" Class *@
                <vc:navigation-menu />
            </div>

            @*Right side of main page*@
            <div class="col-8">
                @RenderBody()
            </div>
        </div>
    </div>


    @*Footer to look cute and call in any scripts needed*@
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Hilton the Amazonian
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>